### PR TITLE
Drop rework engine

### PR DESCRIPTION
**Pull request by TrySound**
It's been a while since the last release. We can safely drop rework
engine with major bump. Some dependencies are gone.

### CODE REVIEW

**Comment by bholloway** [comment]
@TrySound I was planning to deprecate for v4 (see [here](https://github.com/bholloway/resolve-url-loader/blob/v4-development/packages/resolve-url-loader/README.md#version-4)) but I haven't had a chance to release that. There have been issues with postcss that mean some people have returned to the `rework` engine. But so long as they have v4 then I think we can strand them there.

I am not accepting PRs to `master` right now because I hope to merge `v4-development` into `master` soon.

If you can convert this to an issue then I will create a v5 project and track it there.

**Comment by bholloway** [comment]
With your permission I would like to close the PR 🙏

**Comment by TrySound** [comment]
Great! Can't wait to try v5 😄

**Comment by bholloway** [comment]
@TrySound for visibility on the plan for `rework` I've opened discussion in #160

**Pull request closed without merging**
