### PR TITLE
bump adjust-sourcemap-loader dependency

### PR DESCRIPTION
**Pull request by bholloway**
removes object-path

### CODE REVIEW

**Comment by bholloway** [comment]
Run e2e tests
- [ ] MacOS
- [ ] Windows

**Comment by iwantwin** [comment]
Fixes #170 
Duplicate of #171

**Comment by bholloway** [comment]
This may have an unintended consequence of moving the minimum node version to `8.9` which is what `adjust-sourcemap-loader` is now requiring. Although I do not intend to explicitly move the minimum node version here.

**Comment by crudo** [comment]
You are right, but node version 6 has reached end of life in April 2019.

**Pull request merged**
